//! clap CLI definitions, mirroring the ohpm command surface.

use clap::{Args, Parser, Subcommand};

#[derive(Parser, Debug)]
#[command(name = "ohpm-rs", version, about = "ohpm-rs (OpenHarmony package manager), a Rust reimplementation of ohpm")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Subcommand, Debug)]
pub enum Command {
    /// Publish a package to the registry.
    Publish(PublishArgs),
    /// Pre-verify package content without publishing.
    Prepublish(PrepublishArgs),
    /// Build a har package from a source directory.
    Pack(PackArgs),
    /// Create an oh-package.json5 file.
    Init(InitArgs),
    /// Manage the ohpm configuration file.
    Config(ConfigArgs),
    /// Log in with a private key and store the access token.
    Login(LoginArgs),
    /// Unpublish a package from the registry.
    Unpublish(UnpublishArgs),
    /// Display information about a package.
    Info(InfoArgs),
    /// Display the dependency graph (basic).
    List(ListArgs),
    /// Test network connectivity to the registry.
    Ping(PingArgs),
    /// Print the effective oh_modules folder.
    Root,
    /// Bump the package version.
    Version(VersionArgs),
    /// Manage the ohpm cache folder.
    Cache(CacheArgs),
}

#[derive(Args, Debug, Clone)]
pub struct PublishArgs {
    /// The har or tgz package file.
    #[arg(value_name = "har_or_tgz_file")]
    pub file: String,
    /// Add the specified tag to the current version.
    #[arg(short = 't', long)]
    pub tag: Option<String>,
    /// Specify the registry when publishing.
    #[arg(long = "publish_registry")]
    pub publish_registry: Option<String>,
    /// Specify the publish id generated by the registry.
    #[arg(long = "publish_id")]
    pub publish_id: Option<String>,
    /// The private SSH key path corresponding to the publish_id.
    #[arg(long = "key_path")]
    pub key_path: Option<String>,
    /// The private key PEM content directly (alternative to --key_path;
    /// prefer the OHPM_KEY_CONTENT env var in CI).
    #[arg(long = "key_content", allow_hyphen_values = true)]
    pub key_content: Option<String>,
    /// The private key passphrase (prefer the OHPM_KEY_PASSPHRASE env var in
    /// CI; this flag is visible in the process list).
    #[arg(long)]
    pub passphrase: Option<String>,
    /// Network request timeout in milliseconds.
    #[arg(long)]
    pub timeout: Option<u64>,
}

#[derive(Args, Debug, Clone)]
pub struct PrepublishArgs {
    /// The har or tgz package file (or a source directory).
    #[arg(value_name = "har_or_tgz_file")]
    pub file: String,
}

#[derive(Args, Debug, Clone)]
pub struct PackArgs {
    /// Source directory containing oh-package.json5 (defaults to the current
    /// package directory). Mutually exclusive with --workspace/--filter.
    #[arg(value_name = "source_dir")]
    pub source: Option<String>,
    /// Output directory for the har (defaults to the current directory).
    #[arg(long)]
    pub output: Option<String>,
    /// Pack every publishable workspace member (workspace batch mode).
    #[arg(long)]
    pub workspace: bool,
    /// Only pack the listed workspace members (by name, comma-separated).
    #[arg(long, value_delimiter = ',')]
    pub filter: Vec<String>,
}

#[derive(Args, Debug, Clone)]
pub struct InitArgs {
    /// Create a default oh-package.json5 file.
    #[arg(short = 'y', long)]
    pub yes: bool,
    /// Create a package with the specified group.
    #[arg(short = 'g', long, value_name = "group_name")]
    pub group: Option<String>,
}

#[derive(Args, Debug, Clone)]
pub struct ConfigArgs {
    /// Subcommand: set | get | delete | list | ls.
    #[arg(value_name = "action")]
    pub action: Option<String>,
    #[arg(value_name = "key")]
    pub key: Option<String>,
    #[arg(value_name = "value")]
    pub value: Option<String>,
    /// Output in JSON format (for list).
    #[arg(short = 'j', long)]
    pub json: bool,
}

#[derive(Args, Debug, Clone)]
pub struct LoginArgs {
    /// The registry to log in to.
    #[arg(long = "publish_registry")]
    pub publish_registry: Option<String>,
    /// Publish id generated by the registry.
    #[arg(long = "publish_id")]
    pub publish_id: Option<String>,
    /// Private key path.
    #[arg(long = "key_path")]
    pub key_path: Option<String>,
    /// The private key PEM content directly (alternative to --key_path;
    /// prefer the OHPM_KEY_CONTENT env var in CI).
    #[arg(long = "key_content", allow_hyphen_values = true)]
    pub key_content: Option<String>,
    /// Private key passphrase.
    #[arg(long)]
    pub passphrase: Option<String>,
}

#[derive(Args, Debug, Clone)]
pub struct UnpublishArgs {
    /// Package name, optionally with @version.
    #[arg(value_name = "pkg")]
    pub pkg: Option<String>,
    /// Unpublish all versions without a specified version.
    #[arg(short = 'f', long)]
    pub force: bool,
    #[arg(long = "publish_registry")]
    pub publish_registry: Option<String>,
    #[arg(long = "publish_id")]
    pub publish_id: Option<String>,
    #[arg(long = "key_path")]
    pub key_path: Option<String>,
    /// The private key PEM content directly (alternative to --key_path;
    /// prefer the OHPM_KEY_CONTENT env var in CI).
    #[arg(long = "key_content", allow_hyphen_values = true)]
    pub key_content: Option<String>,
    #[arg(long)]
    pub timeout: Option<u64>,
}

#[derive(Args, Debug, Clone)]
pub struct InfoArgs {
    /// Package name, optionally with @version or @tag:<tag>.
    #[arg(value_name = "pkg")]
    pub pkg: String,
    /// Optional field to display.
    #[arg(value_name = "field")]
    pub field: Option<String>,
    #[arg(long)]
    pub registry: Option<String>,
    #[arg(long)]
    pub timeout: Option<u64>,
}

#[derive(Args, Debug, Clone)]
pub struct ListArgs {
    /// Specify the max depth of the dependency graph.
    #[arg(short = 'd', long)]
    pub depth: Option<u32>,
    /// Output in JSON format.
    #[arg(short = 'j', long)]
    pub json: bool,
    /// Print the dependency graph for all modules.
    #[arg(short = 'r', long)]
    pub recursive: bool,
}

#[derive(Args, Debug, Clone)]
pub struct PingArgs {
    #[arg(long)]
    pub registry: Option<String>,
    #[arg(long)]
    pub timeout: Option<u64>,
}

#[derive(Args, Debug, Clone)]
pub struct VersionArgs {
    /// newversion | major | minor | patch
    #[arg(value_name = "action")]
    pub action: Option<String>,
    /// Bump every package in the workspace to the same version (workspace
    /// unified mode).
    #[arg(long)]
    pub workspace: bool,
    /// Only bump the listed workspace packages (by name, comma-separated).
    #[arg(long, value_delimiter = ',')]
    pub filter: Vec<String>,
    /// Pre-release identifier for pre* / prerelease actions, e.g. --preid beta.
    #[arg(long)]
    pub preid: Option<String>,
}

#[derive(Args, Debug, Clone)]
pub struct CacheArgs {
    /// Subcommand: clean.
    #[arg(value_name = "action")]
    pub action: Option<String>,
}
