//! clap CLI definitions, mirroring the ohpm command surface.

use clap::{Args, Parser, Subcommand};

#[derive(Parser, Debug)]
#[command(name = "ohpm-rs", version, about = "ohpm-rs (OpenHarmony package manager), a Rust reimplementation of ohpm")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Subcommand, Debug)]
pub enum Command {
    /// Publish a package to the registry.
    Publish(PublishArgs),
    /// Pre-verify package content without publishing.
    Prepublish(PrepublishArgs),
    /// Build a har package from a source directory.
    Pack(PackArgs),
    /// Create an oh-package.json5 file.
    Init(InitArgs),
    /// Manage the ohpm configuration file.
    Config(ConfigArgs),
    /// Log in with a private key and store the access token.
    Login(LoginArgs),
    /// Unpublish a package from the registry.
    Unpublish(UnpublishArgs),
    /// Display information about a package.
    Info(InfoArgs),
    /// Display the dependency graph (basic).
    List(ListArgs),
    /// Test network connectivity to the registry.
    Ping(PingArgs),
    /// Print the effective oh_modules folder.
    Root,
    /// Bump the package version.
    Version(VersionArgs),
    /// Manage the ohpm cache folder.
    Cache(CacheArgs),
    /// Delete all 'oh_modules' directories and the 'oh-package-lock.json5'
    /// file in the current project.
    #[command(alias = "cls")]
    Clean(CleanArgs),
    /// Install packages from the registry or local sources.
    Install(InstallArgs),
    /// Update package(s) to their latest version based on the specified range.
    Update(UpdateArgs),
    /// Uninstall package(s).
    Uninstall(UninstallArgs),
}

#[derive(Args, Debug, Clone)]
pub struct PublishArgs {
    /// The har or tgz package file (or a source directory). Omit to publish
    /// the current package directory directly from source.
    #[arg(value_name = "har_or_tgz_file")]
    pub file: Option<String>,
    /// Add the specified tag to the current version.
    #[arg(short = 't', long)]
    pub tag: Option<String>,
    /// Specify the registry when publishing.
    #[arg(long = "publish_registry")]
    pub publish_registry: Option<String>,
    /// Specify the publish id generated by the registry.
    #[arg(long = "publish_id")]
    pub publish_id: Option<String>,
    /// The private SSH key path corresponding to the publish_id.
    #[arg(long = "key_path")]
    pub key_path: Option<String>,
    /// The private key PEM content directly (alternative to --key_path;
    /// prefer the OHPM_KEY_CONTENT env var in CI).
    #[arg(long = "key_content", allow_hyphen_values = true)]
    pub key_content: Option<String>,
    /// The private key passphrase (prefer the OHPM_KEY_PASSPHRASE env var in
    /// CI; this flag is visible in the process list).
    #[arg(long)]
    pub passphrase: Option<String>,
    /// Network request timeout in milliseconds.
    #[arg(long)]
    pub timeout: Option<u64>,
    /// Publish every publishable workspace member (workspace batch mode).
    #[arg(long)]
    pub workspace: bool,
    /// Only publish the listed workspace members (by name, comma-separated).
    #[arg(long, value_delimiter = ',')]
    pub filter: Vec<String>,
    /// Validate everything without uploading (no network requests).
    #[arg(long)]
    pub dry_run: bool,
}

#[derive(Args, Debug, Clone)]
pub struct PrepublishArgs {
    /// The har or tgz package file (or a source directory). Omit to validate
    /// the current package directory directly from source.
    #[arg(value_name = "har_or_tgz_file")]
    pub file: Option<String>,
    /// Validate every publishable workspace member (workspace batch mode).
    #[arg(long)]
    pub workspace: bool,
    /// Only validate the listed workspace members (by name, comma-separated).
    #[arg(long, value_delimiter = ',')]
    pub filter: Vec<String>,
}

#[derive(Args, Debug, Clone)]
pub struct PackArgs {
    /// Source directory containing oh-package.json5 (defaults to the current
    /// package directory). Mutually exclusive with --workspace/--filter.
    #[arg(value_name = "source_dir")]
    pub source: Option<String>,
    /// Output directory for the har (defaults to the current directory).
    #[arg(long)]
    pub output: Option<String>,
    /// Pack every publishable workspace member (workspace batch mode).
    #[arg(long)]
    pub workspace: bool,
    /// Only pack the listed workspace members (by name, comma-separated).
    #[arg(long, value_delimiter = ',')]
    pub filter: Vec<String>,
}

#[derive(Args, Debug, Clone)]
pub struct InitArgs {
    /// Create a default oh-package.json5 file.
    #[arg(short = 'y', long)]
    pub yes: bool,
    /// Create a package with the specified group.
    #[arg(short = 'g', long, value_name = "group_name")]
    pub group: Option<String>,
}

#[derive(Args, Debug, Clone)]
pub struct ConfigArgs {
    /// Subcommand: set | get | delete | list | ls.
    #[arg(value_name = "action")]
    pub action: Option<String>,
    #[arg(value_name = "key")]
    pub key: Option<String>,
    #[arg(value_name = "value")]
    pub value: Option<String>,
    /// Output in JSON format (for list).
    #[arg(short = 'j', long)]
    pub json: bool,
}

#[derive(Args, Debug, Clone)]
pub struct LoginArgs {
    /// The registry to log in to.
    #[arg(long = "publish_registry")]
    pub publish_registry: Option<String>,
    /// Publish id generated by the registry.
    #[arg(long = "publish_id")]
    pub publish_id: Option<String>,
    /// Private key path.
    #[arg(long = "key_path")]
    pub key_path: Option<String>,
    /// The private key PEM content directly (alternative to --key_path;
    /// prefer the OHPM_KEY_CONTENT env var in CI).
    #[arg(long = "key_content", allow_hyphen_values = true)]
    pub key_content: Option<String>,
    /// Private key passphrase.
    #[arg(long)]
    pub passphrase: Option<String>,
}

#[derive(Args, Debug, Clone)]
pub struct UnpublishArgs {
    /// Package name, optionally with @version.
    #[arg(value_name = "pkg")]
    pub pkg: Option<String>,
    /// Unpublish all versions without a specified version.
    #[arg(short = 'f', long)]
    pub force: bool,
    #[arg(long = "publish_registry")]
    pub publish_registry: Option<String>,
    #[arg(long = "publish_id")]
    pub publish_id: Option<String>,
    #[arg(long = "key_path")]
    pub key_path: Option<String>,
    /// The private key PEM content directly (alternative to --key_path;
    /// prefer the OHPM_KEY_CONTENT env var in CI).
    #[arg(long = "key_content", allow_hyphen_values = true)]
    pub key_content: Option<String>,
    #[arg(long)]
    pub timeout: Option<u64>,
}

#[derive(Args, Debug, Clone)]
pub struct InfoArgs {
    /// Package name, optionally with @version or @tag:<tag>.
    #[arg(value_name = "pkg")]
    pub pkg: String,
    /// Optional field to display.
    #[arg(value_name = "field")]
    pub field: Option<String>,
    #[arg(long)]
    pub registry: Option<String>,
    #[arg(long)]
    pub timeout: Option<u64>,
}

#[derive(Args, Debug, Clone)]
pub struct ListArgs {
    /// Package name, optionally with @version.
    #[arg(value_name = "pkg")]
    pub pkg: Option<String>,
    /// Specify the max depth of the dependency graph.
    #[arg(short = 'd', long)]
    pub depth: Option<u32>,
    /// Output in JSON format.
    #[arg(short = 'j', long)]
    pub json: bool,
    /// Print the dependency graph for all modules.
    #[arg(short = 'r', long)]
    pub recursive: bool,
}

#[derive(Args, Debug, Clone)]
pub struct PingArgs {
    #[arg(long)]
    pub registry: Option<String>,
    #[arg(long)]
    pub timeout: Option<u64>,
}

#[derive(Args, Debug, Clone)]
pub struct VersionArgs {
    /// newversion | major | minor | patch
    #[arg(value_name = "action")]
    pub action: Option<String>,
    /// Bump every package in the workspace to the same version (workspace
    /// unified mode).
    #[arg(long)]
    pub workspace: bool,
    /// Only bump the listed workspace packages (by name, comma-separated).
    #[arg(long, value_delimiter = ',')]
    pub filter: Vec<String>,
    /// Pre-release identifier for pre* / prerelease actions, e.g. --preid beta.
    #[arg(long)]
    pub preid: Option<String>,
}

#[derive(Args, Debug, Clone)]
pub struct CacheArgs {
    /// Subcommand: clean | path | status | add.
    #[arg(value_name = "action")]
    pub action: Option<String>,
    /// Package(s) for `add`: [<@group>/]<pkg>[@<version> | @tag:<tag>].
    #[arg(value_name = "pkg")]
    pub pkg: Vec<String>,
}

#[derive(Args, Debug, Clone)]
pub struct CleanArgs {
    /// Do not delete the 'oh-package-lock.json5' file.
    #[arg(long = "keep-lockfile", alias = "kl")]
    pub keep_lockfile: bool,
    /// Clean every workspace member (workspace batch mode).
    #[arg(long)]
    pub workspace: bool,
    /// Only clean the listed workspace members (by name, comma-separated).
    #[arg(long, value_delimiter = ',')]
    pub filter: Vec<String>,
}

#[derive(Args, Debug, Clone)]
pub struct InstallArgs {
    /// Packages, folders, or har/tgz files:
    /// [<@group>/]<pkg>[@<version> | @tag:<tag>] | <folder> | <har file>.
    #[arg(value_name = "pkg")]
    pub pkg: Vec<String>,
    /// Save the package to devDependencies in oh-package.json5.
    #[arg(long = "save-dev")]
    pub save_dev: bool,
    /// Save the package to dependencies in oh-package.json5.
    #[arg(long = "save-prod")]
    pub save_prod: bool,
    /// Save the package to dynamicDependencies in oh-package.json5.
    #[arg(long = "save-dynamic")]
    pub save_dynamic: bool,
    /// Do not save to oh-package.json5.
    #[arg(long = "no-save")]
    pub no_save: bool,
    /// Do actual copy instead of symbolic link for source-code dependencies.
    #[arg(long = "no-link")]
    pub no_link: bool,
    /// Install the dependencies in the concurrently safe mode (the
    /// reference's flag is always true — the option surface is kept for
    /// parity).
    #[arg(long = "experimental-concurrently-safe")]
    pub experimental_concurrently_safe: bool,
    /// Install the dependencies of all modules in the project.
    #[arg(long)]
    pub all: bool,
    /// Package root directory (defaults to the nearest directory upward that
    /// contains oh-package.json5).
    #[arg(long)]
    pub prefix: Option<String>,
    /// The parameter file path (parameterization).
    #[arg(long = "parameter-file")]
    pub parameter_file: Option<String>,
    /// Install packages in the context of the specific target path
    /// (dependencyMap.json5 targets).
    #[arg(long = "target_path")]
    pub target_path: Option<String>,
    /// Specify the registry.
    #[arg(long)]
    pub registry: Option<String>,
    /// Specify the local store (cache) directory.
    #[arg(long)]
    pub cache: Option<String>,
    /// Network request timeout in milliseconds.
    #[arg(long = "fetch_timeout")]
    pub fetch_timeout: Option<u64>,
    /// Whether to verify the TLS certificate.
    #[arg(long = "strict_ssl")]
    pub strict_ssl: Option<bool>,
    /// Maximum concurrent tasks.
    #[arg(long = "max_concurrent")]
    pub max_concurrent: Option<u64>,
    /// Number of retries for network requests.
    #[arg(long = "retry_times")]
    pub retry_times: Option<u32>,
    /// Retry interval in milliseconds.
    #[arg(long = "retry_interval")]
    pub retry_interval: Option<u64>,
}

#[derive(Args, Debug, Clone)]
pub struct UpdateArgs {
    /// Package names to update (without versions).
    #[arg(value_name = "pkg")]
    pub pkg: Vec<String>,
    /// Update a package or all dependencies in the current module and install
    /// the dependencies of all modules in the project.
    #[arg(long)]
    pub all: bool,
    /// Update a package or all dependencies in all modules.
    #[arg(long = "all-modules")]
    pub all_modules: bool,
    /// Update the dependencies whose tag matches the regular expression.
    #[arg(long = "tag-filter")]
    pub tag_filter: Option<String>,
    /// Package root directory.
    #[arg(long)]
    pub prefix: Option<String>,
    /// Specify the registry.
    #[arg(long)]
    pub registry: Option<String>,
    /// Specify the local store (cache) directory.
    #[arg(long)]
    pub cache: Option<String>,
    #[arg(long = "fetch_timeout")]
    pub fetch_timeout: Option<u64>,
    #[arg(long = "strict_ssl")]
    pub strict_ssl: Option<bool>,
    #[arg(long = "max_concurrent")]
    pub max_concurrent: Option<u64>,
    #[arg(long = "retry_times")]
    pub retry_times: Option<u32>,
    #[arg(long = "retry_interval")]
    pub retry_interval: Option<u64>,
}

#[derive(Args, Debug, Clone)]
pub struct UninstallArgs {
    /// Package names to uninstall (without versions).
    #[arg(value_name = "pkg")]
    pub pkg: Vec<String>,
    /// Do not save to oh-package.json5.
    #[arg(long = "no-save")]
    pub no_save: bool,
    /// Uninstall a package in the current module and install the dependencies
    /// of all modules in the project.
    #[arg(long)]
    pub all: bool,
    /// Package root directory.
    #[arg(long)]
    pub prefix: Option<String>,
    /// Specify the registry.
    #[arg(long)]
    pub registry: Option<String>,
    /// Specify the local store (cache) directory.
    #[arg(long)]
    pub cache: Option<String>,
    #[arg(long = "fetch_timeout")]
    pub fetch_timeout: Option<u64>,
    #[arg(long = "strict_ssl")]
    pub strict_ssl: Option<bool>,
    #[arg(long = "max_concurrent")]
    pub max_concurrent: Option<u64>,
    #[arg(long = "retry_times")]
    pub retry_times: Option<u32>,
    #[arg(long = "retry_interval")]
    pub retry_interval: Option<u64>,
}
