//! The `oh-package-lock.json5` lockfile, mirroring `lib/core/locker/PackageLocker.js`,
//! `lib/core/locker/PackageLockerManager.js` and `lib/core/locker/index.js`.
//!
//! Byte-compatibility notes (the reference serializes with
//! `JSON.stringify(obj, null, 2)` via `FsUtil.writeFile`, which normalizes
//! line endings to `\n` and appends nothing):
//!
//! * top-level key order: `meta`, `lockfileVersion`, `ATTENTION`,
//!   `specifiers`, `packages`;
//! * `specifiers`/`packages` keys are sorted (`Object.keys().sort()`, i.e.
//!   UTF-16 code-unit order; UTF-8 byte order is identical for the ASCII keys
//!   that occur in practice);
//! * package entries carry the fields of `getLockPkgFromNodeData.js` in its
//!   literal order; empty `dependencies`/`dynamicDependencies` are dropped;
//! * sorting is applied when `meta.stableOrder` (default) or the
//!   `lockfile_stable_order` config is set.

use std::collections::{BTreeMap, HashSet};
use std::path::{Path, PathBuf};

use serde::Serialize;

use crate::constants::{LOCK_JSON, LATEST, MY_PACKAGE_JSON};
use crate::error::{OhpmError, Result};
use crate::install::spec::{is_local_dependency, is_protocol_spec, parse_dependency, parse_inner, OhpaType};

/// `LockFile.defaultLockJson.ATTENTION`.
pub const LOCKFILE_ATTENTION: &str =
    "THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.";

/// `LockFile.version`.
pub const LOCKFILE_VERSION: u64 = 3;

/// A `packages` entry (mirrors `getLockPkgFromNodeData.js` key order).
#[derive(Debug, Clone, Default, Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LockPkg {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub integrity: Option<String>,
    /// `resolved || ""` — always present.
    #[serde(default)]
    pub resolved: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shasum: Option<String>,
    /// "ohpm" | "local" (npm white-list deferred).
    #[serde(default)]
    pub registry_type: String,
    #[serde(rename = "resolved_hsp", default, skip_serializing_if = "Option::is_none")]
    pub resolved_hsp: Option<String>,
    #[serde(rename = "integrity_hsp", default, skip_serializing_if = "Option::is_none")]
    pub integrity_hsp: Option<String>,
    /// Metadata-derived entries may carry dev dependencies; node-derived
    /// entries never do, so this is only serialized when non-empty.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub dev_dependencies: BTreeMap<String, String>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub dependencies: BTreeMap<String, String>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub dynamic_dependencies: BTreeMap<String, String>,
    #[serde(rename = "packageType", skip_serializing_if = "Option::is_none")]
    pub package_type: Option<String>,
    #[serde(rename = "hspType", skip_serializing_if = "Option::is_none")]
    pub hsp_type: Option<String>,
    #[serde(rename = "isDebugHsp", skip_serializing_if = "Option::is_none")]
    pub is_debug_hsp: Option<bool>,
    /// `addOrRemoveOverrideDependencyMapTag` — written only when the node's
    /// deps were modified by `exclusions` / `overrideDependencyMap`.
    #[serde(
        rename = "maskedByOverrideDependencyMap",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub masked_by_override_dependency_map: Option<bool>,
    /// Unknown fields round-trip (HSP/debug fields of future versions).
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl LockPkg {
    pub fn new(name: &str, version: &str) -> Self {
        Self {
            name: name.to_string(),
            version: version.to_string(),
            ..Default::default()
        }
    }
}

/// The lockfile document (`meta` + `lockfileVersion` + `ATTENTION` +
/// `specifiers` + `packages`).
#[derive(Debug, Clone, Default)]
pub struct Lockfile {
    pub meta_stable_order: bool,
    /// Written only when present (fresh lockfiles carry `false`).
    pub meta_enable_unified_lockfile: Option<bool>,
    /// `name@<declared spec>` -> `name@<pinned version | relative path>`.
    pub specifiers: BTreeMap<String, String>,
    pub packages: BTreeMap<String, LockPkg>,
}

impl Lockfile {
    pub fn is_empty(&self) -> bool {
        self.specifiers.is_empty() && self.packages.is_empty()
    }
}

/// `PackageLockerManager.createPkgLocker` + `mergeLockJson` — load an existing
/// v3 lockfile, or start from the default shape. A non-v3 file is ignored
/// (and later overwritten, since the file exists).
pub fn read_lockfile(path: &Path) -> Option<Lockfile> {
    let text = std::fs::read_to_string(path).ok()?;
    let value: serde_json::Value = json5::from_str(&text).ok()?;
    if value.get("lockfileVersion").and_then(|v| v.as_u64()) != Some(LOCKFILE_VERSION) {
        return None;
    }
    let mut lf = Lockfile::default();
    match value.get("meta") {
        Some(meta) => {
            lf.meta_stable_order = meta
                .get("stableOrder")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            lf.meta_enable_unified_lockfile =
                meta.get("enableUnifiedLockfile").and_then(|v| v.as_bool());
        }
        // Old v3 files without `meta` get `{stableOrder: false}` (no sorting).
        None => lf.meta_stable_order = false,
    }
    if let Some(specifiers) = value.get("specifiers") {
        if let Ok(map) = serde_json::from_value(specifiers.clone()) {
            lf.specifiers = map;
        }
    }
    if let Some(packages) = value.get("packages") {
        if let Ok(map) = serde_json::from_value(packages.clone()) {
            lf.packages = map;
        }
    }
    Some(lf)
}

/// `PackageLockerManager.createUnifiedPkgLocker` — the project-root locker
/// for unified-lockfile mode: an existing unified lockfile is adopted
/// (`mergeLockJson`), the per-module lockfiles are merged otherwise
/// (`mergeUntiedLockJson`).
pub fn load_unified_lockfile(
    project_root: &Path,
    module_roots: &[PathBuf],
    lock_name: &str,
) -> Locker {
    let mut locker = Locker::load_with_lock_name(project_root, lock_name);
    locker.lockfile.meta_enable_unified_lockfile = Some(true);
    match read_lockfile(&project_root.join(lock_name)) {
        // `mergeLockJson` — a fresh locker adopts an existing unified lockfile
        // wholesale (its stableOrder meta included).
        Some(existing) if existing.meta_enable_unified_lockfile == Some(true) => {
            locker.lockfile = existing;
            locker.lockfile.meta_enable_unified_lockfile = Some(true);
            locker
        }
        // `mergeUntiedLockJson` — merge the per-module lockfiles.
        _ => merge_untied_lock_json(locker, project_root, module_roots, lock_name),
    }
}

/// `mergeUntiedLockJson` — merge the per-module lockfiles into the unified
/// locker: local dependency keys/paths become project-root-relative, and a
/// specifier key with conflicting values drops both entries.
fn merge_untied_lock_json(
    mut locker: Locker,
    project_root: &Path,
    module_roots: &[PathBuf],
    lock_name: &str,
) -> Locker {
    let mut dropped: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for module_root in module_roots {
        let Some(d) = read_lockfile(&module_root.join(lock_name)) else {
            continue;
        };
        // The project-root module's lockfile becomes the base.
        if locker.lockfile.specifiers.is_empty()
            && locker.lockfile.packages.is_empty()
            && module_root == project_root
        {
            locker.lockfile = d;
            continue;
        }
        for (raw_key, raw_value) in &d.specifiers {
            let Ok(key) = parse_dependency(raw_key, module_root) else {
                continue;
            };
            let Ok(value) = parse_dependency(raw_value, module_root) else {
                continue;
            };
            let mut key_str = raw_key.clone();
            let mut value_str = raw_value.clone();
            if matches!(key.ohpa_type, OhpaType::File | OhpaType::SourceCode) {
                key_str = format!("{}@{}", key.name, relative_spec(project_root, &key.fetch_spec));
            }
            if matches!(value.ohpa_type, OhpaType::File | OhpaType::SourceCode) {
                value_str = format!("{}@{}", key.name, relative_spec(project_root, &value.fetch_spec));
            }
            match locker.lockfile.specifiers.get(&key_str) {
                Some(existing) if existing != &value_str => {
                    locker.lockfile.specifiers.remove(&key_str);
                    dropped.insert(key_str);
                }
                Some(_) => {}
                None => {
                    if !dropped.contains(&key_str) {
                        locker.lockfile.specifiers.insert(key_str, value_str);
                    }
                }
            }
        }
        for (raw_key, pkg) in &d.packages {
            let Ok(key) = parse_dependency(raw_key, module_root) else {
                continue;
            };
            let mut key_str = raw_key.clone();
            let mut pkg = pkg.clone();
            if matches!(key.ohpa_type, OhpaType::File | OhpaType::SourceCode) {
                let rel = relative_spec(project_root, &key.fetch_spec);
                pkg.resolved = rel.clone();
                key_str = format!("{}@{rel}", key.name);
            }
            locker.lockfile.packages.insert(key_str, pkg);
        }
        locker.lockfile.meta_stable_order =
            locker.lockfile.meta_stable_order || d.meta_stable_order;
    }
    locker
}

/// `PackageLocker.flush`'s write step — `JSON.stringify(lockJson, null, 2)`
/// with LF line endings.
pub fn write_lockfile(path: &Path, lf: &Lockfile) -> Result<()> {
    let doc = SerializeLockfile(lf);
    let json = serde_json::to_string_pretty(&doc)?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, json)?;
    Ok(())
}

/// The serialized top-level shape, in the reference's key order.
struct SerializeLockfile<'a>(&'a Lockfile);

impl Serialize for SerializeLockfile<'_> {
    fn serialize<S: serde::Serializer>(&self, s: S) -> std::result::Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let lf = self.0;
        let mut st = s.serialize_struct("lockfile", 5)?;
        st.serialize_field("meta", &SerializeMeta(lf))?;
        st.serialize_field("lockfileVersion", &LOCKFILE_VERSION)?;
        st.serialize_field("ATTENTION", LOCKFILE_ATTENTION)?;
        st.serialize_field("specifiers", &lf.specifiers)?;
        st.serialize_field("packages", &lf.packages)?;
        st.end()
    }
}

struct SerializeMeta<'a>(&'a Lockfile);

impl Serialize for SerializeMeta<'_> {
    fn serialize<S: serde::Serializer>(&self, s: S) -> std::result::Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let lf = self.0;
        let mut st = s.serialize_struct("meta", 2)?;
        st.serialize_field("stableOrder", &lf.meta_stable_order)?;
        if let Some(unified) = lf.meta_enable_unified_lockfile {
            st.serialize_field("enableUnifiedLockfile", &unified)?;
        }
        st.end()
    }
}

/// `PackageLockerManager.relativeSpec` — the lockfile key form of a spec:
/// local deps become slash-normalized paths relative to the module root.
pub fn relative_spec(root: &Path, spec: &str) -> String {
    // Protocol specs (`workspace:`, `ohpm:`, git URLs, pinned commits) never
    // go through path normalization.
    if is_protocol_spec(spec) {
        return spec.to_string();
    }
    if !is_local_dependency(spec) {
        return spec.to_string();
    }
    let mut spec = spec;
    if let Some(rest) = spec.strip_prefix("file:") {
        spec = rest;
    }
    let p = Path::new(spec);
    if p.is_absolute() {
        slash(&relative_path(root, p))
    } else {
        slash(spec)
    }
}

/// `PackageLockerManager.parseSpecKey` — split `[@scope/]name@version`.
/// Returns `(name_without_scope, version)`; the scope is dropped in the
/// `pkgName` field exactly like the reference.
pub fn parse_spec_key(spec: &str) -> Result<(String, String)> {
    let rest = if spec.starts_with('@') && spec.contains('/') {
        let i = spec.find('/').ok_or_else(|| OhpmError::locker_invalid_spec(spec))?;
        &spec[i + 1..]
    } else {
        spec
    };
    let at = rest.find('@').ok_or_else(|| OhpmError::locker_invalid_spec(spec))?;
    if at == 0 {
        return Err(OhpmError::locker_invalid_spec(spec));
    }
    Ok((rest[..at].to_string(), rest[at + 1..].to_string()))
}

/// `PackageLockerManager.resolveLockSpec` — resolve a specifier *value*
/// (`name@pinned`) back to its absolute form for local deps.
pub fn resolve_lock_spec(root: &Path, spec_value: &str) -> Result<String> {
    if spec_value.is_empty() {
        return Err(OhpmError::locker_invalid_specifier(""));
    }
    let (name, version) = parse_spec_key(spec_value)?;
    if is_local_dependency(&version) {
        Ok(format!("{name}@{}", resolve_local(root, &version)))
    } else {
        Ok(spec_value.to_string())
    }
}

/// Resolve a local spec to a normalized absolute path
/// (`path.resolve(root, spec)`).
fn resolve_local(root: &Path, spec: &str) -> String {
    crate::workspace::resolve_file_spec(root, &format!("file:{spec}"))
        .to_string_lossy()
        .into_owned()
}

/// `path.relative` with forward slashes.
fn relative_path(from: &Path, to: &Path) -> String {
    // Canonicalize both sides: workspace member dirs are canonicalized at
    // discovery while the module root may still carry a symlinked prefix
    // (macOS `/var` -> `/private/var`), which would zero the common prefix
    // and produce a wrong `../..`-chain instead of the true relative path.
    let from = from.canonicalize().unwrap_or_else(|_| from.to_path_buf());
    let to = to.canonicalize().unwrap_or_else(|_| to.to_path_buf());
    let from: Vec<_> = from.components().collect();
    let to: Vec<_> = to.components().collect();
    let mut common = 0;
    while common < from.len() && common < to.len() && from[common] == to[common] {
        common += 1;
    }
    let mut parts: Vec<String> = (0..from.len() - common).map(|_| "..".to_string()).collect();
    for c in &to[common..] {
        parts.push(c.as_os_str().to_string_lossy().into_owned());
    }
    if parts.is_empty() {
        ".".to_string()
    } else {
        parts.join("/")
    }
}

fn slash(s: &str) -> String {
    s.replace('\\', "/")
}

/// The per-module locker state (mirrors `PackageLocker` + the manager glue for
/// the non-unified path).
#[derive(Debug, Clone)]
pub struct Locker {
    pub module_root: PathBuf,
    pub lockfile: Lockfile,
    /// The lockfile existed before this install (even when not v3).
    pub was_present: bool,
    /// The lockfile file name (`oh-package-lock.json5`, or the target variant).
    lock_name: String,
    visited_spec_keys: HashSet<String>,
    visited_pkg_keys: HashSet<String>,
}

impl Locker {
    /// `syncLoadLockers` + `createPkgLocker` for a single module root.
    ///
    /// `createPkgLocker`'s `mergeLockJson` keeps the file's `stableOrder` but
    /// always stamps `enableUnifiedLockfile` with `shouldUseUnifiedLockfile()`
    /// (false in the non-unified mode); fresh lockers get the default shape
    /// (`stableOrder: true`).
    pub fn load(module_root: &Path) -> Locker {
        Self::load_with_lock_name(module_root, LOCK_JSON)
    }

    /// `getLockFileName` — target mode names the lockfile
    /// `oh-package-<target>-lock.json5`.
    pub fn load_with_lock_name(module_root: &Path, lock_name: &str) -> Locker {
        let path = module_root.join(lock_name);
        let was_present = path.exists();
        let parsed = read_lockfile(&path);
        let mut lockfile = parsed.clone().unwrap_or_default();
        if parsed.is_none() {
            lockfile.meta_stable_order = true;
        }
        // Fresh lockers and `createPkgLocker`'s merge path both stamp the
        // unified flag with `shouldUseUnifiedLockfile()` (false here).
        lockfile.meta_enable_unified_lockfile = Some(false);
        Locker {
            module_root: module_root.to_path_buf(),
            lockfile,
            was_present,
            lock_name: lock_name.to_string(),
            visited_spec_keys: HashSet::new(),
            visited_pkg_keys: HashSet::new(),
        }
    }

    /// `getLockSpec` — the specifier value for `name@spec` (marks the key
    /// visited).
    pub fn get_lock_spec(&mut self, name: &str, spec: &str) -> Option<String> {
        let key = format!("{name}@{spec}");
        self.visited_spec_keys.insert(key.clone());
        self.lockfile.specifiers.get(&key).cloned()
    }

    /// `getLockPkg` — the locked package for `name@spec` (also marks the
    /// specifier key visited via `getLockSpec`).
    pub fn get_lock_pkg(&mut self, name: &str, spec: &str) -> Option<(String, LockPkg)> {
        let value = self.get_lock_spec(name, spec)?;
        let pkg = self.lockfile.packages.get(&value)?.clone();
        Some((value, pkg))
    }

    /// `updateLockSpec` — `name@spec` -> `name@pinned`.
    pub fn update_lock_spec(&mut self, name: &str, spec: &str, pinned: &str) {
        self.update_lock_spec_named(name, name, spec, pinned);
    }

    /// `updateLockSpec` with separate key/value names — aliases write the
    /// specifier KEY under the declared name but the VALUE under the real
    /// package name (`foo@ohpm:bar@^1.0.0` -> `bar@1.2.3`), so the flush
    /// prune matches the packages key.
    pub fn update_lock_spec_named(&mut self, key_name: &str, value_name: &str, spec: &str, pinned: &str) {
        let key = format!("{key_name}@{spec}");
        self.visited_spec_keys.insert(key.clone());
        self.lockfile
            .specifiers
            .insert(key, format!("{value_name}@{pinned}"));
    }

    /// `updateLockPkg` — `name@version` -> package entry.
    ///
    /// Local deps' `resolved` is relativized against the module root: the
    /// reference stores the relative fetch spec (`file:../lib` -> `../lib`)
    /// so the lockfile stays valid across machines, and real ohpm shares the
    /// node's relative path through `getLockPkgFromNodeData`. Registry/git
    /// entries pass through untouched.
    pub fn update_lock_pkg(&mut self, name: &str, version: &str, mut pkg: LockPkg) {
        if pkg.registry_type == "local" {
            pkg.resolved = relative_spec(&self.module_root, &pkg.resolved);
        }
        self.lockfile
            .packages
            .insert(format!("{name}@{version}"), pkg);
    }

    /// `deleteSpecifier` — remove a specifier key (used by
    /// `checkAndReassignResolvedField`).
    pub fn delete_specifier(&mut self, key: &str) {
        self.lockfile.specifiers.remove(key);
    }

    /// `deletePackage` — remove a `name@version` package entry (used by
    /// `resolveVersionConflict2LockFile`).
    pub fn delete_package(&mut self, key: &str) {
        self.lockfile.packages.remove(key);
    }

    /// `clearSpecifiers` — used on `--all`/update.
    pub fn clear_specifiers(&mut self) {
        self.lockfile.specifiers.clear();
        self.lockfile.meta_stable_order = true;
        self.lockfile.meta_enable_unified_lockfile = Some(true);
    }

    /// `flush` — prune unvisited specifiers/packages, sort, and write (only
    /// when the file existed or packages are non-empty). Empty dependency
    /// maps are dropped at serialization time.
    pub fn flush(&mut self) -> Result<()> {
        let Locker {
            lockfile,
            visited_spec_keys,
            visited_pkg_keys,
            lock_name,
            ..
        } = self;
        // Specifiers: drop unvisited; collect the surviving values as the
        // visited package keys (the reference additionally protects inner-file
        // dep packages when `enable_lock_inner_pkg_version` is off — deferred).
        lockfile.specifiers.retain(|key, value| {
            if !visited_spec_keys.contains(key) {
                return false;
            }
            visited_pkg_keys.insert(value.clone());
            true
        });
        lockfile
            .packages
            .retain(|key, _| visited_pkg_keys.contains(key));
        let path = self.module_root.join(lock_name);
        if !self.was_present && lockfile.packages.is_empty() {
            return Ok(());
        }
        write_lockfile(&path, lockfile)
    }
}

/// `getLockFileName.js` — the per-module lockfile name (target mode changes
/// it to `oh-package-<target>-lock.json5`).
pub fn lock_file_name(target_name: &str) -> String {
    if target_name.is_empty() {
        LOCK_JSON.to_string()
    } else {
        format!("oh-package-{target_name}-lock.json5")
    }
}

/// The lockfile's manifest requirement: a module root always has
/// `oh-package.json5` (used by callers to validate the prefix).
pub fn has_manifest(dir: &Path) -> bool {
    dir.join(MY_PACKAGE_JSON).is_file()
}

/// The requested-version `latest` marker (re-export for callers).
pub fn is_latest_spec(spec: &str) -> bool {
    spec == LATEST
}

/// Parse a specifier value `name@version` for the resolver (wraps the raw
/// parse; local paths are handled by the caller via `where_dir`).
pub fn parse_spec_value(value: &str, where_dir: &Path) -> Result<crate::install::spec::Spec> {
    parse_inner(value, where_dir).map_err(|_| OhpmError::locker_invalid_spec(value))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn write(dir: &Path, rel: &str, content: &str) {
        let p = dir.join(rel);
        fs::create_dir_all(p.parent().unwrap()).unwrap();
        fs::write(p, content).unwrap();
    }

    fn sample_lockfile() -> Lockfile {
        let mut lf = Lockfile::default();
        lf.meta_stable_order = true;
        lf.meta_enable_unified_lockfile = Some(false);
        lf.specifiers.insert(
            "@ohos/foo@^1.2.0".to_string(),
            "@ohos/foo@1.2.3".to_string(),
        );
        lf.specifiers.insert("bar@latest".to_string(), "bar@2.0.0".to_string());
        let mut pkg = LockPkg::new("@ohos/foo", "1.2.3");
        pkg.integrity = Some("sha512-AAAA".to_string());
        pkg.resolved = "https://ohpm.openharmony.cn/ohpm/@ohos/foo/-/foo-1.2.3.tgz".to_string();
        pkg.shasum = Some("abc123".to_string());
        pkg.registry_type = "ohpm".to_string();
        pkg.dependencies.insert("@ohos/bar".to_string(), "1.0.0".to_string());
        lf.packages.insert("@ohos/foo@1.2.3".to_string(), pkg);
        lf.packages.insert(
            "bar@2.0.0".to_string(),
            LockPkg {
                name: "bar".to_string(),
                version: "2.0.0".to_string(),
                resolved: String::new(),
                registry_type: "ohpm".to_string(),
                ..Default::default()
            },
        );
        lf
    }

    #[test]
    fn serialize_byte_exact() {
        let lf = sample_lockfile();
        let json = serde_json::to_string_pretty(&SerializeLockfile(&lf)).unwrap();
        assert_eq!(
            json,
            r#"{
  "meta": {
    "stableOrder": true,
    "enableUnifiedLockfile": false
  },
  "lockfileVersion": 3,
  "ATTENTION": "THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
  "specifiers": {
    "@ohos/foo@^1.2.0": "@ohos/foo@1.2.3",
    "bar@latest": "bar@2.0.0"
  },
  "packages": {
    "@ohos/foo@1.2.3": {
      "name": "@ohos/foo",
      "version": "1.2.3",
      "integrity": "sha512-AAAA",
      "resolved": "https://ohpm.openharmony.cn/ohpm/@ohos/foo/-/foo-1.2.3.tgz",
      "shasum": "abc123",
      "registryType": "ohpm",
      "dependencies": {
        "@ohos/bar": "1.0.0"
      }
    },
    "bar@2.0.0": {
      "name": "bar",
      "version": "2.0.0",
      "resolved": "",
      "registryType": "ohpm"
    }
  }
}"#
        );
        // No trailing newline (FsUtil.writeFile appends nothing).
        assert!(!json.ends_with('\n'));
    }

    #[test]
    fn roundtrip_and_version_gate() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(LOCK_JSON);
        let lf = sample_lockfile();
        write_lockfile(&path, &lf).unwrap();

        let loaded = read_lockfile(&path).expect("load");
        assert_eq!(loaded.specifiers, lf.specifiers);
        assert_eq!(loaded.packages.len(), 2);
        let pkg = &loaded.packages["@ohos/foo@1.2.3"];
        assert_eq!(pkg.name, "@ohos/foo");
        assert_eq!(pkg.dependencies["@ohos/bar"], "1.0.0");

        // A v2 file is ignored.
        write(dir.path(), LOCK_JSON, "{ \"lockfileVersion\": 2 }");
        assert!(read_lockfile(&path).is_none());

        // A file without meta gets stableOrder=false.
        write(
            dir.path(),
            LOCK_JSON,
            r#"{ "lockfileVersion": 3, "specifiers": {}, "packages": {} }"#,
        );
        let loaded = read_lockfile(&path).expect("load v3 no meta");
        assert!(!loaded.meta_stable_order);
        assert!(loaded.meta_enable_unified_lockfile.is_none());
    }

    #[test]
    fn locker_flush_prunes() {
        let dir = TempDir::new().unwrap();
        write_lockfile(&dir.path().join(LOCK_JSON), &sample_lockfile()).unwrap();
        let mut locker = Locker::load(dir.path());
        assert!(locker.was_present);
        // Touch only `bar@latest`; `@ohos/foo@^1.2.0` must be pruned.
        locker.update_lock_spec("bar", "latest", "2.1.0");
        let mut pkg = LockPkg::new("bar", "2.1.0");
        pkg.registry_type = "ohpm".to_string();
        pkg.dependencies.insert("baz".to_string(), "1.0.0".to_string());
        pkg.dynamic_dependencies.insert("dyn".to_string(), "1.0.0".to_string());
        locker.update_lock_pkg("bar", "2.1.0", pkg);
        locker.flush().unwrap();

        let text = fs::read_to_string(dir.path().join(LOCK_JSON)).unwrap();
        assert!(text.contains("\"bar@latest\": \"bar@2.1.0\""));
        assert!(!text.contains("@ohos/foo"));
        assert!(!text.contains("2.0.0"));
        assert!(text.contains("\"dependencies\": {"));
        assert!(text.contains("\"dynamicDependencies\": {"));

        // A second flush with no writes leaves an empty package map -> the
        // file still exists, so it is written with empty maps.
        let mut locker2 = Locker::load(dir.path());
        locker2.flush().unwrap();
        let text2 = fs::read_to_string(dir.path().join(LOCK_JSON)).unwrap();
        assert!(text2.contains("\"specifiers\": {}"));
        assert!(text2.contains("\"packages\": {}"));
    }

    #[test]
    fn fresh_locker_writes_nothing_when_empty() {
        let dir = TempDir::new().unwrap();
        let mut locker = Locker::load(dir.path());
        assert!(!locker.was_present);
        locker.flush().unwrap();
        assert!(!dir.path().join(LOCK_JSON).exists());
    }

    #[test]
    fn spec_key_and_relative() {
        assert_eq!(parse_spec_key("@ohos/foo@1.2.3").unwrap(), ("foo".into(), "1.2.3".into()));
        assert_eq!(parse_spec_key("foo@^1.0.0").unwrap(), ("foo".into(), "^1.0.0".into()));
        assert!(parse_spec_key("nonsense").is_err());

        assert_eq!(relative_spec(Path::new("/proj"), "latest"), "latest");
        assert_eq!(relative_spec(Path::new("/proj"), "^1.0.0"), "^1.0.0");
        assert_eq!(relative_spec(Path::new("/proj"), "/proj/../lib"), "../lib");
        assert_eq!(relative_spec(Path::new("/proj/entry"), "/proj/lib"), "../lib");
        assert_eq!(relative_spec(Path::new("/proj"), "file:../lib"), "../lib");

        assert_eq!(
            resolve_lock_spec(Path::new("/proj"), "foo@1.2.3").unwrap(),
            "foo@1.2.3"
        );
        assert_eq!(
            resolve_lock_spec(Path::new("/proj"), "foo@../lib").unwrap(),
            "foo@/lib"
        );
    }

    #[test]
    fn parse_spec_key_protocol_shapes() {
        // Git URLs with user@host, alias specs with nested @, and values.
        assert_eq!(
            parse_spec_key("foo@git+ssh://user@host/repo.git").unwrap(),
            ("foo".into(), "git+ssh://user@host/repo.git".into())
        );
        assert_eq!(
            parse_spec_key("foo@ohpm:bar@^1.0.0").unwrap(),
            ("foo".into(), "ohpm:bar@^1.0.0".into())
        );
        assert_eq!(parse_spec_key("bar@1.2.3").unwrap(), ("bar".into(), "1.2.3".into()));
        assert_eq!(
            parse_spec_key("foo@0123456789abcdef0123456789abcdef01234567").unwrap(),
            ("foo".into(), "0123456789abcdef0123456789abcdef01234567".into())
        );
        assert_eq!(
            parse_spec_key("foo@workspace:^1.0.0").unwrap(),
            ("foo".into(), "workspace:^1.0.0".into())
        );
        // Scoped names keep the scope on the name side.
        assert_eq!(
            parse_spec_key("@ohos/foo@1.2.3").unwrap(),
            ("foo".into(), "1.2.3".into())
        );
    }

    #[test]
    fn clears_specifiers_sets_unified() {
        let mut locker = Locker::load(Path::new("/proj"));
        locker.update_lock_spec("foo", "^1.0.0", "1.2.3");
        locker.clear_specifiers();
        assert!(locker.lockfile.specifiers.is_empty());
        assert!(locker.lockfile.meta_stable_order);
        assert_eq!(locker.lockfile.meta_enable_unified_lockfile, Some(true));
    }
}

#[cfg(test)]
mod unified_tests {
    use super::*;

    #[test]
    fn untied_lockfile_merge() {
        let dir = tempfile::TempDir::new().unwrap();
        let proj = dir.path().join("proj");
        std::fs::create_dir_all(proj.join("entry")).unwrap();
        std::fs::create_dir_all(proj.join("lib1")).unwrap();
        // Two per-module lockfiles: foo in both, entry (local) in lib1.
        let lf1 = Lockfile {
            meta_stable_order: true,
            meta_enable_unified_lockfile: Some(false),
            specifiers: BTreeMap::from([
                ("@ohos/foo@^1.0.0".to_string(), "@ohos/foo@1.2.3".to_string()),
            ]),
            packages: BTreeMap::from([(
                "@ohos/foo@1.2.3".to_string(),
                LockPkg {
                    name: "@ohos/foo".to_string(),
                    version: "1.2.3".to_string(),
                    registry_type: "ohpm".to_string(),
                    ..Default::default()
                },
            )]),
        };
        write_lockfile(&proj.join("entry/oh-package-lock.json5"), &lf1).unwrap();
        let lf2 = Lockfile {
            meta_stable_order: false,
            meta_enable_unified_lockfile: Some(false),
            specifiers: BTreeMap::from([
                ("entry@../entry".to_string(), "entry@<abs>".to_string()),
            ]),
            packages: BTreeMap::new(),
        };
        write_lockfile(&proj.join("lib1/oh-package-lock.json5"), &lf2).unwrap();

        let roots = vec![proj.join("entry"), proj.join("lib1")];
        let locker = load_unified_lockfile(&proj, &roots, LOCK_JSON);
        assert_eq!(locker.lockfile.meta_enable_unified_lockfile, Some(true));
        assert!(locker.lockfile.specifiers.contains_key("@ohos/foo@^1.0.0"));
        assert!(locker.lockfile.packages.contains_key("@ohos/foo@1.2.3"));
        // The module lockfiles are untouched.
        assert!(proj.join("entry/oh-package-lock.json5").is_file());
    }

    #[test]
    fn existing_unified_lockfile_is_adopted() {
        let dir = tempfile::TempDir::new().unwrap();
        let proj = dir.path().join("proj");
        std::fs::create_dir_all(&proj).unwrap();
        let lf = Lockfile {
            meta_stable_order: true,
            meta_enable_unified_lockfile: Some(true),
            specifiers: BTreeMap::from([(
                "foo@^1.0.0".to_string(),
                "foo@1.0.0".to_string(),
            )]),
            packages: BTreeMap::new(),
        };
        write_lockfile(&proj.join(LOCK_JSON), &lf).unwrap();
        let locker = load_unified_lockfile(&proj, &[proj.clone()], LOCK_JSON);
        assert_eq!(locker.lockfile.meta_enable_unified_lockfile, Some(true));
        assert!(locker.lockfile.specifiers.contains_key("foo@^1.0.0"));
    }
}
